### ISSUE TITLE
Prediction Bar doesn't work at all. Dictation key works

### ISSUE THREAD

**Issue by mansonstein1** [vyolit/Kayoko#7]
**Describe the bug:**prediction bar doesn't  show anything 

**Steps to reproduce the behavior:**

**System information:**
- iOS version:15.1.1
- Device:12
- Jailbreak:xina15

**Comment by Traurige** [comment]
I can only recommend you to either try disabling all other tweaks to look for conflicts or restore rootfs and try again. It works on my 3 test devices and apparently everyone else.

**Comment by nn9dev** [comment]
I also have this issue. iPhone SE 2020, iOS 14.5.1. It's worth noting that when I first installed the tweak, it did in fact show up, but I switched to Dictation button because the items in the bar didn't switch over to predictive text when I started typing (and I wasn't sure if that was intentional or not). I swapped back over because sometimes the menu would randomly pop up and I wanted to make sure I wasn't fat fingering the dictation button, but it didn't ever show up in the predictive bar. The only keyboard related tweak I have installed is EmojiPort.

**Comment by Traurige** [comment]
> I also have this issue. iPhone SE 2020, iOS 14.5.1. It's worth noting that when I first installed the tweak, it did in fact show up, but I switched to Dictation button because the items in the bar didn't switch over to predictive text when I started typing (and I wasn't sure if that was intentional or not). I swapped back over because sometimes the menu would randomly pop up and I wanted to make sure I wasn't fat fingering the dictation button, but it didn't ever show up in the predictive bar. The only keyboard related tweak I have installed is EmojiPort.

I still can’t do anything about it, as long as I don’t experience it myself.

**Comment by zgibberish** [comment]
> I also have this issue. iPhone SE 2020, iOS 14.5.1. It's worth noting that when I first installed the tweak, it did in fact show up, but I switched to Dictation button because the items in the bar didn't switch over to predictive text when I started typing (and I wasn't sure if that was intentional or not). I swapped back over because sometimes the menu would randomly pop up and I wanted to make sure I wasn't fat fingering the dictation button, but it didn't ever show up in the predictive bar. The only keyboard related tweak I have installed is EmojiPort.

same here on 6s (14.4.2) odysseyra1n

**Comment by vyolit** [comment]
I still have never experienced this ever since the initial release, and thus will close this issue.
